eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8012
logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway.route.RouteDefinitionLocator: INFO
          gateway: TRACE

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      # Booking Service Route
      - id: booking-service
        uri: lb://booking-service
        predicates:
          - Path=/api/v1/bookings/**
      # Parking Details Service Route
      - id: parking-details-service
        uri: lb://parking-details-service
        predicates:
          - Path=/api/v1/parkings/**
      # Payment Service Route
      - id: payment-service
        uri: lb://payment-service
        predicates:
          - Path=/api/v1/payments/**
      # Discovery Server Route
      - id: discovery-service
        uri: http://localhost:8761
        predicates:
          - Path=/eureka/web
        filters: SetPath=/
      # Discovery Server Static Resources Route
      - id: discovery-service-static
        uri: http://localhost:8761
        predicates:
          - Path=/eureka/**
  security:
    oauth2:
      resourceserver:
        jwt.issuer-uri: http://localhost:8180/realms/ticket-digi-realm
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
management:
  endpoints:
    web:
      exposure:
        include: prometheus